const CONSTANT = {
	EXCHANGE_RATE: "TY_GIA",
	CHARGING_FEE: "CHARGING_FEE",
	FEE_BY_WEIGHT: "FEE_BY_WEIGHT",
	BANK_SUPPORT: "BANK",
	ORDER_STATUS: {
		DA_DUYET: 1,
		DA_DAT_COC: 2,
		DA_MUA_HANG: 3,
		HANG_DA_VE_KHO_TQ: 4,
		HANG_DA_VE_KHO_VN: 5,
		SAN_SANG_GIAO_HANG: 6,
		CHO_XU_LY_KHIEU_NAI: 7,
		DA_KET_THUC: 8,
		DA_HUY: 9,
	},
	BANK_TYPE: {
		NAP_TIEN: 1,
		RUT_TIEN: 0,
		DAT_COC: 2,
		TAT_TOAN: 3,
		HOAN_TIEN: 4,
	},
};

export default CONSTANT;
