const CONSTANT = {
	EXCHANGE_RATE: "TY_GIA",
	CHARGING_FEE: "CHARGING_FEE",
	FEE_BY_WEIGHT: "FEE_BY_WEIGHT",
	BANK_SUPPORT: "BANK",
	ORDER_STATUS: {
		DA_DUYET: 1,
		DA_DAT_COC: 2,
		DA_MUA_HANG: 3,
		HANG_DA_VE_KHO_TQ: 4,
		HANG_DA_VE_KHO_VN: 5,
		SAN_SANG_GIAO_HANG: 6,
		CHO_XU_LY_KHIEU_NAI: 7,
		DA_KET_THUC: 8,
		DA_HUY: 9,
	},
	BANK_TYPE: {
		NAP_TIEN: 1,
		RUT_TIEN: 0,
		DAT_COC: 2,
		TAT_TOAN: 3,
		HOAN_TIEN: 4,
	},
	TRANSACTION_STATUS: {
		REJECT: 0,
		PENDING: 1,
		APPROVE: 2,
	},
	PACKAGE_STATUS: {
		NB_PHAT_HANH: 1,
		NHAP_KHO_TQ: 2,
		GUI_BAO_TQ: 3,
		NHAN_BAO_VIETNAM: 4,
		DA_KIEM: 5,
		NHAP_KHO_VN: 6,
		DA_GIAO: 7,
		DETELE: 0,
	},
	BAG_STATUS: {
		MO: 1,
		GUI_HANG: 2,
		NHAN_HANG: 3,
		DONG: 0,
	},
	ORDER_QUERY_CRITERIA: {
		WITHOUT_SHOP: "WITHOUT_SHOP",
		WITHOUT_DOMESTIC_FEE: "WITHOUT_DOMESTIC_FEE",
		WITHOUT_SHIP_CODE: "WITHOUT_SHIP_CODE",
	},
	DELIVERY_STATUS: {
		CHUA_GIAO: 1,
		DA_GIAO: 2,
	},
	ROLE: {
		KHACH_HANG: 0,
		ADMIN: 1,
		NHAN_VIEN_TU_VAN: 2,
		NHAN_VIEN_MUA_HANG: 3,
		NHAN_VIEN_KHO: 4,
	},
	ROLE_STAFF: {
		NHAN_VIEN_TU_VAN: 2,
		NHAN_VIEN_MUA_HANG: 3,
		NHAN_VIEN_KHO: 4,
	},
};

export default CONSTANT;
